### PR TITLE
Adding DRAMFS stdin

### PR DESCRIPTION
**Pull request by dpetrisko**
Stdin is defined as fd 0, common uart schematic is to return -1 on empty entry. return on complete len or string termination

### CODE REVIEW

**Comment by farzamgl** [comment]
Is _read from stdin supposed to be blocking? if not there's no reason for the while loop.

**Comment by dpetrisko** [comment]
The intention here is to use this with scanf, which i assume is blocking

**Comment by farzamgl** [comment]
my concern is that other non-blocking functions may call _read and if scanf does its blocking by checking the return value of read then it may change the behaviour of other functions. scanf would be still working though.
Other than this looks good.

**Comment by dpetrisko** [comment]
what's the normal behavior of reading stdin in a non-dramfs system?

**Comment by farzamgl** [comment]
I think the default is blocking but for example, you can use fcntl to change the read() to non-blocking. That's why I assume _read() also should be non-blocking if it's called by higher-level functions. Or maybe it checks a flag.

**Comment by dpetrisko** [comment]
It looks like the default for linux is blocking: https://www.linuxtoday.com/blog/blocking-and-non-blocking-i-0/

>By default, read() waits until at least one byte is available to return to the application; this default is called “blocking” mode. Alternatively, individual file descriptors can be switched to “non-blocking” mode, which means that a read() on a slow file will return immediately, even if no bytes are available.

**Comment by dpetrisko** [comment]
@farzamgl After a ton of trial and error, this seems to be the correct implementation. It blocks for 1 byte, but then will just return on end of queue. Also interestingly, getchar _must_ return an integer, because EOF == -1 needs to be distinguished from unsigned char 255. We handle this in the bp dramfs_getchar routine, so it is invisible here, but modify the signatures accordingly

**Comment by dpetrisko** [comment]
Appears to work in this demo: https://github.com/black-parrot-sdk/bp-demos/pull/1

**Comment by taylor-bsg** [comment]
Normally you would modify: 

https://github.com/bespoke-silicon-group/bsg_newlib_dramfs/blob/dramfs/libgloss/dramfs/dramfs/dramfs_fdtable.c

to also store the O_NONBLOCK flag when open or fcntl is called. Then when you do read on the I/O, you would check the flag to decide whether to return even if no data is present (and maybe set errno to be EAGAIN.)

**Comment by dpetrisko** [comment]
I’m fine adding that. Is there a spec / manpage somewhere you can point me to?

**Comment by dpetrisko** [comment]
I think I’ve got it working with open, but it doesn’t look like fcntl is implemented in PanicRoom? Not sure if I’m reading that right but I don’t see in libgloss

**Comment by taylor-bsg** [comment]
Yeah seems like it is not supported by default. We can add it if we ever
need it…

**Comment by dpetrisko** [comment]
gotcha. Does this look good other than that?

**Review by taylor-bsg — APPROVED** [review]

**Pull request merged**
